---
- hosts: all
  vars:
    allowed_ssh_networks:
      - 192.168.122.0/24
      
  tasks:
    # Perform updating of all software installed on server. This is the very first step to be taken to secure your server.
    - name: Perform full software updates
        package:
        name: '*'
        state: latest
        
    # To make privilege escalation hard, we create a new user with sudo permissions
    - name: create new user 
      user:
        name: test
        shell: /bin/bash
        home: /home/test
        create_home: yes
        state: present

    - name: Give sudo to user test
      lineinfile:
        path: /etc/sudoers.d/test
        line: 'test ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        create: yes
        validate: '/usr/sbin/visudo -csf %s'
    
    # This is part of legal advice to be clear to a malicious hacker.
    - name: Set a MOTD
      copy:
        dest: /etc/motd
        src: etc/motd
        owner: root
        group: root
        mode: 0644

    - name: Set a login banner
      copy:
        dest: "{{ item }}"
        src: etc/issue
        owner: root
        group: root
        mode: 0644
      with_items:
        - /etc/issue
        - /etc/issue.net
    
    - name: Add SSH public key for user
      authorized_key:
        user: admin
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
    
    - name: Add SSH port to internal zone
      firewalld:
        zone: internal
        service: ssh
        state: enabled
        immediate: yes
        permanent: yes

    - name: Add permitted networks to internal zone
      firewalld:
        zone: internal
        source: "{{ item }}"
        state: enabled
        immediate: yes
        permanent: yes
      with_items: "{{ allowed_ssh_networks }}"
...
